version: "3.9"
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    image: tilt.dev/express-redis-app
    links:
      - redis
    ports:
      - $PORT:$PORT
    env_file:
      - app.env
    environment:
      - PORT=$PORT
    command:
      sh -c 'node server.js'

