version: "3.9"
services:
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - database
  app:
    image: tilt.dev/express-redis-app
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=3000
    command:
      sh -c 'node server.js'
    networks:
      - database
networks:
  database:
